//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor 5.8.1.
// cliteral_res.rc

#define IDD_CSTRLITERAL                     100

#define IDI_MAINICON                        100

#define IDR_EXAMPLES_MENU                   100

#define IDS_TITLE                           100
#define IDS_SYNTAX_ERROR                    101
#define IDS_INVALID_ESCAPE                  102
#define IDS_QUOTE_NOT_FOUND                 103
#define IDS_QUOTE_NOT_CLOSED                104
#define IDS_PREFIX_MISMATCH                 105
#define IDS_NOT_QUOTED                      106
#define IDS_TEXT_LENGTH                     107
#define IDS_BINARY_SIZE                     108
#define IDS_BYTES                           109
#define IDS_BYTE_SEQUENCE                   110
#define IDS_MANUAL_URL                      111
#define IDS_INVALID_CHARSET                 112
#define IDS_DELIMITER_TOO_LONG              113
#define IDS_RAW_LITERAL_NOT_CLOSED          114
#define IDS_ANSI_STRING                     115
#define IDS_WIDE_STRING                     116
#define IDS_UTF8_STRING                     117
#define IDS_UTF16_STRING                    118
#define IDS_UTF32_STRING                    119
#define IDS_TRIGRAPH_FOUND                  120

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    101
        #define _APS_NEXT_COMMAND_VALUE     100
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
